name: conexaoentrebancos_beta
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  dotenv: ^4.2.0
  mysql_client: ^0.0.27
  http: ^1.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
